import java.util.Arrays;
import java.util.HashMap;
import java.util.HashSet;
import java.util.Map;

public class Main {
    public static void main(String[] args) {

        /*

        Given a string on each line parse the first number and last number in the string to a two digit number
        If there is only one number consider the first and last to be that particular two digit number
        Total the sum of every two digit number on each line

        1abc2
        pqr3stu8vwx
        a1b2c3d4e5f
        treb7uchet


         */

        String original = "dqfournine5four2jmlqcgv\n" +
                "7ggzdnjxndfive\n" +
                "twofive4threenine\n" +
                "dttwonezbgmcseven5seven\n" +
                "5vsrcnine\n" +
                "95zzbjck\n" +
                "gkoneight4fivekvktltnine\n" +
                "fiverckdmgbfthjdqpmpgdkmcklqtqc365mqtwo\n" +
                "44sevenhvstcbgkhm5foureight11\n" +
                "dprrtrngrfccz4eight4two8sthmfive\n" +
                "6twofive4seven7nine\n" +
                "four1sevenbfbnqvkbfoursix7\n" +
                "12xpdghpeightqvztrsslgsix5smlgfjhcpst\n" +
                "8dhzdtbeightfour3\n" +
                "pttdtmhg4\n" +
                "6eightsevendbtbxnqzxds6\n" +
                "twothree5nxglqlc9\n" +
                "nine6lqhnvbpxoneseveneightsxjfkz4vr\n" +
                "three28jxdmlqfmc619eightwol\n" +
                "26jtdpgqjzshncxvlljfour\n" +
                "qxvpsctgx1\n" +
                "28286qdjjlgtdtnsm3hk\n" +
                "9hcj6nine\n" +
                "nineseven9sqtrpfour\n" +
                "one1eight4sixzltzrkthree\n" +
                "threevlgfxhnf6seven6nine68\n" +
                "sixonesxxbxvfnkt8\n" +
                "8fivefivefour7sxsrvdrz\n" +
                "oneone7\n" +
                "ndtkjbsix6three9gdsjlljtj6six\n" +
                "cfmrfgjqgrzcmsix5\n" +
                "3threefour62three3vrmnmgx\n" +
                "kckdghseventwo1758\n" +
                "mdbqqjmpvonetwo1six31fourntbfb\n" +
                "lkjhjdthree3\n" +
                "qthseven61mpfnnhm6fivecnhz2\n" +
                "twojrfgzjstjvlngnpqcj8grtnvxmzbxkfrvqmvnmvmbdr\n" +
                "sloneightkqbgcpnv8kqcmzfouronesevenmrfjeight\n" +
                "xdxdxg9seventwo8xcq1\n" +
                "dpdgxzk7\n" +
                "18six3twoone\n" +
                "1twoseven3five\n" +
                "46tkbclbkleight64\n" +
                "tjprpjbshr2seven1pgfqmbmjlvsv\n" +
                "3mbjccssjgtdttvbdhdfxvldpmhcpc\n" +
                "lgfrkpsfvz5ppgqphtwoznjtgxdjpm3\n" +
                "mjmlsevenggsbjbtsix9nineone\n" +
                "jqfqjqhthreenine7eightklkttdkbtmpp1\n" +
                "trptrkbone52eight6\n" +
                "onetmvsrjlbqlninesix8\n" +
                "rone9ktvdqkdgl1\n" +
                "twosix5sixgrfdft54klf4\n" +
                "thrmone3eightsixfive\n" +
                "three4one\n" +
                "ppthg2three1one\n" +
                "7vt426\n" +
                "22foureight6\n" +
                "fourxbhmone56seven8eightnine\n" +
                "vhmsd171rgkhpgfhffnhkvt\n" +
                "xgbzxszsgtthree4\n" +
                "rclzfsn5twoeight\n" +
                "989nine2seven\n" +
                "eighteight5fivensix8\n" +
                "dfxzz5qcqzsjsg\n" +
                "d3eight54\n" +
                "5knflhntzthreeseventwo\n" +
                "threeonefour9oneninebsfpq\n" +
                "hjhgtjgtwotrsffive8hfntm\n" +
                "sixpmhzqrlkrthreefour1pcgvz96\n" +
                "5three31xqcsshkkqtfblffcmcntfour\n" +
                "zghcfvjsfz29nine\n" +
                "3vvvrlrjdztlhqqm88\n" +
                "39nine3seven93\n" +
                "1fqsgnjzrl6lrzsczc\n" +
                "threepldztlnvnzdntqllpr19\n" +
                "ninekgqqrgttfntrhjzlvninelr3\n" +
                "94eighteighteight\n" +
                "two13txmtlqxskhltkrvbjrzm97five\n" +
                "dbmjvszjtb17\n" +
                "twogpfttmhp8two13\n" +
                "four4bqzqscdbctssgxfzjjntwonfcktjrtnxskjpkhvlfjt\n" +
                "ctxxvdsvsvjzchmxvxceightthreembnlg5ninevmcbgsvbh\n" +
                "fpbrpfourqmrfcnpvxg8onehkbbgbsnnt\n" +
                "4zrrgsevenfour\n" +
                "6eight9foureightxlgdn\n" +
                "693rzcnvlfrv\n" +
                "bcftntcfl4jxbccpcmjeightcrxsjscmxdeightmhqbnpdvcfour\n" +
                "six83\n" +
                "xl4\n" +
                "njslckcbdfvkmkdk9eight\n" +
                "ninenineeight4nine\n" +
                "jkzvq3fourzzvdzdft\n" +
                "bfqpb9\n" +
                "eight6nlzdskjfourbmdvcrcgrshbjcxfour2\n" +
                "7zhlxtqtbjxqbszdtwonineeightjcl9\n" +
                "fvcjzxd5sevenfivefqnvkjthreeseven\n" +
                "3cxmpzkng3\n" +
                "8x2\n" +
                "nineeightsevenfourpfzzflnp97\n" +
                "2lkjpfhnpn7gbtztgxtnmclzdtdh33eightstbfrvxqz\n" +
                "nv8\n" +
                "3one7eight\n" +
                "ninetwortwoeightfive8ls\n" +
                "shncxrjqnjttvvzvnl6\n" +
                "ninethree963\n" +
                "mjcfrzjhr33csjxrtmm\n" +
                "five17\n" +
                "84bdfnptmffourfbqslsqeight\n" +
                "onegrzpdj8three2one6fsk\n" +
                "eight33gxpcqvpmeightk\n" +
                "6fbsfclhninetqj5twobxcz\n" +
                "119sixnjmxmvv\n" +
                "825bhceightone4jjdbvrzt2\n" +
                "xjchvkxxhg3sevensixseven3kmgqfmbgmbjnrq\n" +
                "l2\n" +
                "36hcmfnbmsevenfivetxhhgjdlq1khkk\n" +
                "eightj47five4sqtwo\n" +
                "6nineeight9\n" +
                "g2drvxqvpnbjfqxhl\n" +
                "vglkfour9rlmhsnine\n" +
                "onefivezr6rrtddnrg\n" +
                "3threellcbhjhjzqfive5\n" +
                "ggbmhzkcone2\n" +
                "23nclcqvjdzqcrpvsmnpzsfg3five\n" +
                "two5eightddxqgpm8twoseven\n" +
                "nrvtvlhrlr3tvpck1ghbvzxhjkneightgzxgtcddk\n" +
                "7lsxfjhqz\n" +
                "28four\n" +
                "mninetwo3\n" +
                "1fourfxqjpggbpb9threelj\n" +
                "seven3pzkfbqdstdgkrskqrlbg7fzfour4n\n" +
                "btctmct9three6threegkqqkcskfs8chvmcl\n" +
                "threefourskdp6twob\n" +
                "7three6five6eight3\n" +
                "5spkb6\n" +
                "34msnt\n" +
                "5bkqbzpgmjzeight\n" +
                "7g2onefour29fourfour\n" +
                "9fgsixzkbscvbxdsfive6spjfhzxbzvgbvrthreeoneightn\n" +
                "rpbd255fournine\n" +
                "277five\n" +
                "eightseven7sevenllninefive\n" +
                "rpjcmzkthbvdflbhxxkpv3oneplglgmv\n" +
                "xqktwone5jkpxvnptjeight\n" +
                "67one\n" +
                "cgxfhzsnrsjp3kjgzrlbhzh\n" +
                "fiveqqjljzfcmbfqvkscpzscpseven4nine1xvjlgk\n" +
                "tflkxnml5vptclnhkgdg11c2seven\n" +
                "sixeighttdbczshg82threepmjnxrvcnine6\n" +
                "nineone81mkltdkfgxtsevenfive\n" +
                "8zgx\n" +
                "cvb4kv22gp\n" +
                "61bjllhkblllqx8bmr5threesix\n" +
                "9cjfgb1bxncrgfhtmg973\n" +
                "eightninefour5twosixbsvnsndhtghtmfive\n" +
                "seven1bbfrvdcsthree2\n" +
                "cfzd8hvqscjxqf9\n" +
                "sixvfkcgmvqn9vmbzccdmqqgxmfxmnqc95\n" +
                "qqrqnd8twofive7czxtjnmxx\n" +
                "threebdmrlnxnlmdbzbv4\n" +
                "nm91vblgfourtsjp6\n" +
                "six96\n" +
                "sevenrjvbxptl9onecrlz\n" +
                "dvdbrmchgpninenine4onedjcfoneninetwo\n" +
                "hcrrgnlxftwo6four\n" +
                "threehcrfknsnqmg49\n" +
                "2tqbrkxgtdztjkdcnsix6three\n" +
                "mktnzjn58qspzpqdr7\n" +
                "dphvck5fourbmfnskkh72five78\n" +
                "one7seven7\n" +
                "bmpnljsxhfmtwozrhvdv8sjsrmnzlcjvjqcfgffhkjcbx\n" +
                "7one6874\n" +
                "three9tfx4\n" +
                "eight9pqhseightndgbv6\n" +
                "39jgmbzrzkctsix\n" +
                "1676\n" +
                "8xtpdhzfd8three44four8two\n" +
                "sixkvlppxqktkdqjsgjgz5\n" +
                "twoonehbgsdhpxkdvnpr3ncrgbqzfvsbcdsix4\n" +
                "39kpdxsp368seven2\n" +
                "xfljqfbz5tzpldspxvgc\n" +
                "fourqb6twocfljflzqqd\n" +
                "5889cxvxkstlld75rnlgzpgmhcmnx\n" +
                "84zxqsqvb\n" +
                "fiveksvtbqz9934\n" +
                "onefour96four78fourkbkhdhg\n" +
                "h61three2v\n" +
                "nine9jlbrfmgjv2kkfive\n" +
                "bjhktrjmfninexxnjhrvq7\n" +
                "fbcxlvgkkjcmpdcz7\n" +
                "mnleight3oneqqttlp\n" +
                "eighttwolffour1\n" +
                "onetqfghfourbmf5\n" +
                "four1qfive4\n" +
                "9fvp\n" +
                "cxxn5qzcm\n" +
                "one7hzjpnvhtdq\n" +
                "pxmht4fprcftwofive7gsixcqbmrd\n" +
                "three9fivesixrdqrhcqrqbl\n" +
                "6fggvr\n" +
                "ninesixmxvdcqgxcmskl115lskkp\n" +
                "sevenqkmqxltfive191lfbtfvzsixseven\n" +
                "ninemjnjgrlmnlseven5eight9\n" +
                "fhjjtxzksseven7fourthree\n" +
                "rfjksvfour26vqbdrbxc\n" +
                "6zgkfive8mhgxbsm\n" +
                "1njpjv696\n" +
                "4lrthsevendnsmseven\n" +
                "l4hxvjvlfpjmdbvdjzrhkhpmklnine7fourfour\n" +
                "2qtkhnineeightone\n" +
                "fivexhrxrzxht1foursix\n" +
                "sixlzcgllrqlhghzn1hdhgltcntfivefourfive1\n" +
                "dpkzdbzsgq9threecst7znsjgdmmhx1\n" +
                "three497lp388\n" +
                "llnklrkfr3\n" +
                "ltkkv481pzhqzkmhskxlznineninekcbrphlp\n" +
                "fivetwoseven71nineljsbc49\n" +
                "bvqsxnkpmzsevenhdpvfvlb2eight2bdxp3\n" +
                "onefour64\n" +
                "8xfdtfnqvhzkhvszeight5\n" +
                "threethree4two\n" +
                "z5two2fp\n" +
                "fourvjmcghrcfoureight3\n" +
                "lhztwo9dzhpdgn675\n" +
                "jnine4two49sixskv\n" +
                "9phbnnsoneqtpvvzbx5xzc\n" +
                "mtjfxzzhzdjvfmrc1\n" +
                "4ccszl3fiveseven55lfmktz\n" +
                "five27three9mgrnjcsbpd\n" +
                "6eight115five4c\n" +
                "two63fjlkgninepthmone\n" +
                "22ddxpbbpdseven\n" +
                "zg7\n" +
                "five3gvbthree6hjseven\n" +
                "x6six58nine\n" +
                "seveneighteight75three9two9\n" +
                "onevlpdgsnl3\n" +
                "sevenmbvqmjhfnzmgsqp8qnskjzptpppbcfhck2\n" +
                "7bpldrqr6fourpsntqbcqhfive\n" +
                "twothvddvmlbqknrj9pgpsjndbrmrgkgf\n" +
                "sixthree38onefoureightmvdtnn\n" +
                "vkqcnfkkc6\n" +
                "sixeight9\n" +
                "65fouronemklfgqbpgnvlvcvhjcdkq\n" +
                "three5five\n" +
                "981gxpsgqxjktwogninezgnf\n" +
                "cfnnzfnlmfqtwofour8fourxg5\n" +
                "45mpgbgzctwoqlsxmgs8\n" +
                "5nhzlcb6four6pzjjlr4ninej\n" +
                "gnkoneightprhlrseven7\n" +
                "1rzsq1seven3eight\n" +
                "sixnine9eight8eight\n" +
                "lcszz858\n" +
                "pdgbgjxthreethree3threeonengk\n" +
                "8zpzpttrqtwoninek895\n" +
                "634jgvbvr\n" +
                "nine8mvr\n" +
                "5seven2psmtnmzdfivesix\n" +
                "56ninerqrlzqvszrght6zkgtvrphpnvthree\n" +
                "5fiveone\n" +
                "43three\n" +
                "9mdtghvfjdqqbrmeightfour92tlstxvrhthree\n" +
                "b8\n" +
                "ninehpnmdhjqjl5ppptrd\n" +
                "41fournineeightvxxjdthreeeight\n" +
                "ntwonefnsdpnine8sevenbjzxpfive\n" +
                "6oneclxflmxvtwo1\n" +
                "9jbpfnvfsjblmxrprml5\n" +
                "68five7sfgxjqxrcjmninerzgxnhjpzkdhxzbg\n" +
                "1vztdlnone2lhrhx\n" +
                "6lrmdrxqlsttwovsr9eightpbmqcxn\n" +
                "2zjchhdbzhc\n" +
                "tsgntwomdtsjtdrthree9\n" +
                "7threethreedprbrvngxpfour\n" +
                "fivestvv3six\n" +
                "6one9sjlzjtxxnkbckdmc\n" +
                "zxqzmcz3eight\n" +
                "lndh86xphvbnine\n" +
                "fivesix3sixf93hbbptwo\n" +
                "3cxpbl\n" +
                "gsnqeight8kthxzrdkskjkmcmsknine5\n" +
                "67twoxdqninefour\n" +
                "fivefivehtczfmrhvlsevensevennbjkvhz84\n" +
                "cmbgm3eightpbmgjhsp2\n" +
                "fivepdhtcpvg3ninenlhpgdlnnine6fblsmlz\n" +
                "kcnsfsfhjbcffctznvp1\n" +
                "qzrkvhcds4gklftv\n" +
                "xslgkktct7snbxnplbk3five\n" +
                "zspb1sevennine76one\n" +
                "twonxtngxlrftltqggpftj3eight1gsrkbbclll\n" +
                "474jxtncx\n" +
                "bxsqsb8\n" +
                "svsvvtzddklkrxmpd2\n" +
                "xbvjfmcnine2znbqn5eight2smvkgpclvs6\n" +
                "tnlpfivem7\n" +
                "7seveneight2dfiveonesix6\n" +
                "fspcrlcthreej1seven4\n" +
                "7nineeight3hzfour\n" +
                "9fivethree\n" +
                "four5ggbseven\n" +
                "5hsv\n" +
                "1ppkkkhfzn\n" +
                "pkfzkpv9mtktjvrssdftslonebpmhf\n" +
                "8fhfqmzseven\n" +
                "six89htmnpmqsixzvxl\n" +
                "9mbkcbnmptpkhqvvzxftss7\n" +
                "48five\n" +
                "eight8118four7qsjb\n" +
                "cpghtgncpkkxtrvrsgl81eightcfzsjfq6\n" +
                "ninecsthl8onefgpmc\n" +
                "3threehnrone5dzcfdtpf2hdlnrxnmnhjqqqn\n" +
                "5ninesix54\n" +
                "lnzhtwo9446onefivefour\n" +
                "8two427bvcdkckdgz8\n" +
                "6six35seven\n" +
                "six2fcpzhbn6fivekm34\n" +
                "httmgldjfqnnhktmnhj4dsmffzknbq674\n" +
                "9nxrtsmqbcrgghqtx6kdnrfjq\n" +
                "thhmbpjldslpthkfxcfive1zrjqtpvjs8\n" +
                "cjtbcn7five9nlpgsoneone8\n" +
                "seven6eightx176ffrvml8\n" +
                "eight9jntmr4sevenmzjb\n" +
                "mxk51gt\n" +
                "three21foursevendbvm\n" +
                "zqtdz1ninemmhkjfiveeight\n" +
                "98xlpkzb\n" +
                "34two5four2cvtcjfdh\n" +
                "jvndgrtjonethree6\n" +
                "ninefivefive1lfqjqmptxvthree\n" +
                "kkxfqqkf49\n" +
                "3sixseven3dzpvnvt51rnzljdprb\n" +
                "hpzpdrnkthreekct1mqdvljhrls3\n" +
                "six6sjsljgvgzhrzqpsznh3fivejpxsvqccrc\n" +
                "cpvlr7\n" +
                "tdgthree8twofivexxrvct\n" +
                "62sixmt9ninefour\n" +
                "ninesevenfourzfzl43qssqrkktpnzjv\n" +
                "8mfztzthreeldnjgsfseven\n" +
                "356\n" +
                "6vrlthreer9sone6\n" +
                "sixs8six5sevenvnkgbmxj2two\n" +
                "8eightpglsknpxmsixjgqcftmvprjlcdsfks\n" +
                "3dlkbc1\n" +
                "five5eight1\n" +
                "7seven49\n" +
                "ggoneeightgcfnfkgbmlfourdls23\n" +
                "seven6jdpxxkfone\n" +
                "lfive715\n" +
                "2ninefivej2sixeight\n" +
                "ttwonethreethreesixzbqz7\n" +
                "zmbqqcd8ztp46567\n" +
                "nineeight11\n" +
                "zhgsixthreejffqhzdfvfxjpfmjqqkm36one\n" +
                "5vgftjvqkxj6pnctdcrktwoneq\n" +
                "9ptmkf8six\n" +
                "lbjxvnfiverjppbtrhf6xbdnsltlnrqsgmx8q\n" +
                "365pxj63gshpg\n" +
                "vlq5zhgj4\n" +
                "98hc13nnrzfzschg64\n" +
                "2twopq76kpmjdjflkqzxlvjhr\n" +
                "rnvmblqhq1\n" +
                "8j273qfpfkz\n" +
                "dsevenvvdmxhhcd1dkz\n" +
                "lkqhrxkmp96fppvsdtwombkfour\n" +
                "3one7dzpbhsrdf5\n" +
                "159ckggpfzlgntfrddvfiveeightthree9eightwodnp\n" +
                "eightseventhreeseven1\n" +
                "mrzpk8\n" +
                "fmvxth2eight8hjmfkdxjh\n" +
                "3threeone\n" +
                "nine5sixsixnzlqhsc\n" +
                "xtxbgtntwosixfour85\n" +
                "3eighthz4twoqmlhrzsevenkcqhgrghrd\n" +
                "12ldchpqzm\n" +
                "zcfjz5sixmqqmfsv9six6\n" +
                "sixlzcdtd3qlcjqzrtthnine\n" +
                "1one6nine\n" +
                "11xqblttcrdvgb7mdqkphrbdx\n" +
                "xbcc4mtgf5\n" +
                "sevenfourmthree1hgpnmvcvgshzvcsjdbqqgmt\n" +
                "v5xmghdgbkvnine\n" +
                "29mkpfz7\n" +
                "jptwo4lqlrh2onefive7jhcngr\n" +
                "four6twosixsthjqpgh2\n" +
                "pctrvkmc82four2958\n" +
                "12eight3\n" +
                "7jbqeightlbbnpsvvdfrqccb\n" +
                "peightwo6sevenfoursixdmchsd1\n" +
                "53dhphzvhnknt65ninefive\n" +
                "86fivegpnhl\n" +
                "tpcspvvncglcsqjzlqrfivejgfl8zspdltrd7\n" +
                "mhpskcvhn3bkjlmqd\n" +
                "onetwo4lxmsnddzfbxcdcscjxxrzsvvzg3nvtrpncvpmc\n" +
                "fprqq1bpqxvjmblc17\n" +
                "four7ninenineksjcktcbtzsmrfr\n" +
                "3nineccrnhtgg2knczqnnineoneqsgm\n" +
                "4xnkljmg7lmfvrhxm96\n" +
                "five458eighteightxcgrnine\n" +
                "klrzfbrpkmtptdscktmcsqg5xonesix\n" +
                "vtmh1glhzlkmrlgfourpsbhtbrvdz57one\n" +
                "9eight53threethreepgnc\n" +
                "fourseven3fivefq57\n" +
                "5sixsixthreegdsrhkhdlk3six\n" +
                "v9xqhpzkfivebnjslbzh548\n" +
                "jssdslcxxv3sdhbqnine5sixeight2\n" +
                "vr1\n" +
                "eightsoneqrrqfoursixzngsths9three\n" +
                "ltwoltrplmlkzz5sssjmzgcjsixfivejhms\n" +
                "49one\n" +
                "2sevenfivethlgxmxssnvlsfst4\n" +
                "8slfnfsfk\n" +
                "fourszbtpvvlvppsqbsprthreexgrlp3zt4\n" +
                "seveneight8rhonectrmxrjvnnthreetxmfbvxtlt9\n" +
                "twofive6eight9\n" +
                "zqxpxlzjm3hmzjzgoneeight1seventwo\n" +
                "9xbmqqtkstflg6onem2tdfsfjnxdmmzlrcnpm\n" +
                "pgcxbqvvj6\n" +
                "xfsix893\n" +
                "7four1\n" +
                "63five\n" +
                "tr9chvmlhhv6\n" +
                "jxc2six452\n" +
                "11zvz\n" +
                "oneqkhstmkhb11fourninezs37\n" +
                "3mxf3slhhs\n" +
                "sixgdnljsfkfnffp67789nvgc\n" +
                "sxptjdmqfv1eightsevenfpxpdnrtnqkdxhnzdm\n" +
                "grdgt9ninedxnqhrts\n" +
                "8sevenxcsl1\n" +
                "fiveeighttwo5\n" +
                "bgroneight2pgzdpnzgchkq1\n" +
                "5twozc62foursixeight\n" +
                "six61\n" +
                "cbxzoneeight1\n" +
                "hntwonebmslklfkfgpngvffour5\n" +
                "1262ninemdjsrdk\n" +
                "roneightqnjseven2\n" +
                "rmnpjzflcmqdrdseven3\n" +
                "ltwollzgvr1fiveeightjvv7\n" +
                "kkc5fourfive89\n" +
                "cqnnhjxp4dtt\n" +
                "jeightwo1fgtlfpsixtwo9pptcpmjjsixone\n" +
                "832\n" +
                "9eightkhlprvq7seven\n" +
                "ninegeightbfvnvvnpslspcmscvqcqb6\n" +
                "jgksh2lkss6onexznvfhq\n" +
                "flqhlpkzjvq3qvvgvjscr6v9eight\n" +
                "hrgeightwo8\n" +
                "3fvpkbrhqchlbsxhlqfone3eightmhtxbrninerbkrsnxbjg\n" +
                "871eightnineq5f2\n" +
                "6jnonergcjfvkhfive\n" +
                "one47fxgvgmoneoneoneg\n" +
                "5xktmbkqftrlvztctxnqprpnine\n" +
                "eight4tfvsbtmhtwol\n" +
                "rbjdrmbcrs9chvcj7s\n" +
                "eight12bdzqtvnqeight27rpt\n" +
                "fq713oneone6rgrnd\n" +
                "cdt96\n" +
                "dbfrd4rczmbgnmfrltdlpbseven7lqhfive\n" +
                "fourdxxkqjfpjxbcthzhbl67eightzks19\n" +
                "2four5ntghsdcsdrjpbrtrt3bzgbtfnknine\n" +
                "tvmnjgcsixnine8zrc39five\n" +
                "5kcbfkj61three9tsqpvzdd\n" +
                "qsmseventhreeone4twosix\n" +
                "twosix2\n" +
                "jzsmxs9plpsixpqxffive\n" +
                "sixthreeseven4flbct\n" +
                "mpplmsrjvz9\n" +
                "8ttgt9ninesevensevengnprjnvxpjz\n" +
                "8gmpgvbfjcdsnkcth9bbnqsqhqqzeight42\n" +
                "nk5b\n" +
                "four98six83five\n" +
                "415rqgdfsix\n" +
                "mqrkmbvtm668\n" +
                "6453twoone\n" +
                "9fiveeightseven4gsshznxbkb5\n" +
                "seven3ninedgthree\n" +
                "jckgvtvrs3six3trrzfrxfnm8\n" +
                "98fivexxdqpmv74fbthtqqfourvttxnck\n" +
                "fivenineonefour46tccfkrsrpqnxhtm\n" +
                "twobdsqhnscrkbzt19\n" +
                "llmccgn8\n" +
                "6eightoneonen57\n" +
                "meightwo1cjqsm3sixlrr\n" +
                "98842\n" +
                "twofnsvbsxkxrzghhrz29\n" +
                "tzfjthreebkkljhninetwoone6zgpgsgxq\n" +
                "fournkcgf85seventwo\n" +
                "642\n" +
                "four1oneninejbstfcdgjkjtppskglj1\n" +
                "4four9eight2tnphxvfour\n" +
                "sixjhcnxkksxthreeseven1four1\n" +
                "rb34pqtnnfive2sevenone\n" +
                "33sevennlnhrkkbshonefnrqq72\n" +
                "3sevenfourlmqzfdjrq\n" +
                "tmttpfb4mghtcpnine\n" +
                "nhlqlcxff8\n" +
                "fiveone5gxg\n" +
                "fivecrjmsgljxb1mqmffour8mgtdxsjsix\n" +
                "1jdkvzfmbq\n" +
                "ndzqgk6\n" +
                "threeg7twofour2twossldnmthree\n" +
                "5rsltvdtworrglclfpctml3\n" +
                "nine6fourmcqbhbvlmzgnfqtbcs\n" +
                "5eight92\n" +
                "ninefivefour3kbnmrdmxjg2\n" +
                "73vprclhthzz8\n" +
                "ninettjnnkrsix9kvxjknzkmsxtvdn\n" +
                "bgzfv59fhsvcjvlgmhhzph58\n" +
                "threeonefivecgjstcmp57\n" +
                "9onefoursix\n" +
                "sjqjvd4three91\n" +
                "9ccdjqfivefourfive6mrnkjqf\n" +
                "7lzdrzjheightthree6\n" +
                "43\n" +
                "nineb8sixqqsxrpn\n" +
                "fgkj15eight6gggndbjxvthree\n" +
                "one3sevenlfjqmbmssgbzs8pzjptxgvq\n" +
                "77fiveqpjpfdqteighttpfh\n" +
                "2333twonezrr\n" +
                "8p4cxnjvbjlh9ninesix6\n" +
                "ninefour95\n" +
                "67twosevencktwopjcmcxr\n" +
                "9four1threejbrdmtkzn\n" +
                "ninenjhstmmmj3four\n" +
                "4lnqjqtwo3zxfznvp\n" +
                "sixfivesrxnttwochrkdrr7\n" +
                "4three1\n" +
                "tfeightwo9two69five\n" +
                "oneseven3sixfournnpkhhx9\n" +
                "mdl8kfpvthree\n" +
                "fxcxgmq5three3ninehdc8\n" +
                "one9eightfiveonernhbcxjninethree\n" +
                "9three3fcpgxksix\n" +
                "nine346946one\n" +
                "hzkpbmdzdmsfkrbxvs6pnmqsevenlnr\n" +
                "kzsgmsix5\n" +
                "kdjdvvdl2\n" +
                "8lcpfkhdltwo\n" +
                "xjzfbgrmvxprqpflpbk9cnpxdkgmvvjz8vbrjhxvthfsjkk\n" +
                "onefive7\n" +
                "tjqmxncdbmsjznine1zlr\n" +
                "648bhzlqnlvrshdgzonefive\n" +
                "eight2sixtdzznchf1seventwo4\n" +
                "sevenzcmpbfbzdvjlztpx62\n" +
                "5961\n" +
                "97192fivethree\n" +
                "seven1mcxnqqzvpp5\n" +
                "8qn1eightseven\n" +
                "hcrrthreesevenlkvhfbj96twonine9\n" +
                "two8four\n" +
                "hpkttfdpgb16\n" +
                "19oneseven2onerl\n" +
                "347seventwo\n" +
                "eight4threempfbxbssrrkscnc4eight\n" +
                "555qrppcplpgtworxgbgdjdhltwothree\n" +
                "v9627\n" +
                "twoninenine72tkcbk\n" +
                "one5jhczrlqmhr\n" +
                "qnhr4xlckprn9x3bzrdbfrdql9\n" +
                "lgtdv99kmgjjkzfive\n" +
                "lrclbljqqpninerrjptvpfour2\n" +
                "fiveltkcgdvgkeight7seven\n" +
                "twongdsevenfivefive3foureightwonn\n" +
                "8svdmkflj\n" +
                "rlbf4sevennc4jxsskjgktwodsxgtlkthree\n" +
                "seven4nine4fivezjfsjghbcninefk\n" +
                "drghcjthreevstpdfth6sgqtx\n" +
                "zkfthreefptvnvb9five\n" +
                "gjcqspnkztlqdnzl6\n" +
                "6nineqzgvhcnhjxbmtkcfm8one5five5\n" +
                "threesevenseventwoqrcvpvvrdljfone3\n" +
                "v44nlcdx8eight\n" +
                "eightseven3bmfzeightzccxqk6ftlsmfp\n" +
                "seventhreeseven3\n" +
                "7eightgvxcdxzplrthreelqgbhvpqffivefour5\n" +
                "8coneckchx5pfive\n" +
                "xhbbmsvjnonethree4\n" +
                "lnktfknbqfive4seven\n" +
                "8prvncdq97hjjltzreight\n" +
                "2dfktgjgdrvfour\n" +
                "9onesixone\n" +
                "873lsmllvsvp\n" +
                "61dcjgpjvqxj\n" +
                "xtwosixfiveseven2two\n" +
                "p4\n" +
                "threescgqlmkt43one\n" +
                "plffdq4pcqfoureight9one\n" +
                "357qzoneztwo6\n" +
                "6ztllqsixgtfgcr\n" +
                "4nineoneighthch\n" +
                "fivesevenninesevenvpnfkjpeightjsvtqxgrx35\n" +
                "8nsbjtjrhnv36\n" +
                "4eightseven\n" +
                "5rksnms6fgcnrttgl27four9l\n" +
                "3gknvvffflfgdg\n" +
                "8ts98n32one\n" +
                "4vmvthreefourmttwo\n" +
                "sevenskfmmmsjone95\n" +
                "seven4fmnxskg2516four\n" +
                "seveneightzjdnjthreethreefourpj3three\n" +
                "two8one44three3\n" +
                "bffeightwo3twosxljzljbllrtttzsevenxfonetwofive\n" +
                "5eight5sevenfour\n" +
                "4fkxqm\n" +
                "7nine4seven\n" +
                "6eight3sevenfive6pxjlschvhm\n" +
                "5nine7spbqddhrqcbzrvhkrt88\n" +
                "cnpbkmbfour88\n" +
                "41twoeightlgcjfvms\n" +
                "hktvctnine6mzccvthreefournine\n" +
                "1dr66mg5one\n" +
                "five74\n" +
                "bsrrldft858six2oneightm\n" +
                "mmsvhxsm68seven\n" +
                "lnjcnn4fiveninerlsqkcn3\n" +
                "fgzjrlmfjktwofournine5782three\n" +
                "1two8fiveninegndtnzndf41one\n" +
                "kstskp4one9ponejlcqdvgkkdfive\n" +
                "four7two\n" +
                "mzcbhhxgkfourfour34\n" +
                "qvhnpbmvdbgxbnhcgthreesq7dvmdnhl9\n" +
                "1jhmkdmmmjg\n" +
                "6xzpvzvqbrnine8gg1771\n" +
                "sixone9qvfft\n" +
                "6eight152two6sdbl\n" +
                "sevenjlpmzv7\n" +
                "jntrfc5\n" +
                "ztspfjhk4\n" +
                "9fournlslrmlr3\n" +
                "2kqsxx5\n" +
                "3nineshlmjsevenfiveonellrtr\n" +
                "7hcxxjkbsvknbmtwotninesrpsszktzjlntwo\n" +
                "fv1six81\n" +
                "onetwo4eightsixjkgmtvxptnxltqtptncfsix\n" +
                "eightzvmmone3eight9dglsqq5\n" +
                "jvqs4sevendl\n" +
                "551six3oneseveneight\n" +
                "5jtcbrmtbjmrb4sevensmmrctntvz7five\n" +
                "9lrnfive4\n" +
                "twoxfltgdg5six\n" +
                "one4threeeight3eight4stlp\n" +
                "2rpxk95sixslsc895\n" +
                "seven15\n" +
                "1sixsix9sevenkhlnhqtzptwovzrmbr\n" +
                "two55six\n" +
                "twofour3\n" +
                "eight6fiveeightbmrr1sevenk3\n" +
                "4flbntjtfivepzkjplzxn7\n" +
                "ljnpmnskjsixthreehpqdkccffg4sixfszddbz\n" +
                "9gfsqhmonelgvxpkmnhldmthree7\n" +
                "5vthvsrcbxbcrgqnine\n" +
                "six6nine2v\n" +
                "htnvsfmz7dtvthree6sevenfourfourrmsdfhkd\n" +
                "pb24\n" +
                "sbmmdnfvmlfourfivenvcnb3jrctctmrhm\n" +
                "2fourone52hkjvd4\n" +
                "1bhpbmxhtr4eightwolkd\n" +
                "5qrqbxtgppvvcms\n" +
                "mgcgxpmj4dl3zfckcskbqnsknlctwonxsddvhl\n" +
                "6zfv66onetwosixtwoxdx\n" +
                "676jmzcdbcjnfrlrgqzfkmdxz\n" +
                "oneqhgcqjmjq4\n" +
                "three6qvlkksf98\n" +
                "fivesix614s83\n" +
                "threeone9kplvzq28threegcmtrzzlsix\n" +
                "5lxcjrvbthreednttcxfnfiveseven\n" +
                "threeeight5seven5jlhhfour2\n" +
                "xcppxkxqffc6six\n" +
                "fouroneseven1xrdtbvdsix\n" +
                "vfqzhvzclbpj2\n" +
                "5seven8xlhfivetwofivedvlbtvzvs\n" +
                "7bjlrvnncgsseven7six\n" +
                "3qsnhs\n" +
                "2fivefour5\n" +
                "gjgzjs1s\n" +
                "vxhlxvgj39\n" +
                "three1lvnrfrbzj6nine\n" +
                "oneftpcjskxzhv21one2twomshxlh\n" +
                "nine36\n" +
                "ninetwojfqbjkbtrfseven4nkszvtjnffeightwoxdd\n" +
                "eight1eightfiveonerzr4\n" +
                "sevengtwokzcxvvg4\n" +
                "qxkmfdznfive98eightfourprmsixthree\n" +
                "1two743six\n" +
                "274sixqqq62j\n" +
                "sixfour4fourstxrskpxc1eight7\n" +
                "2fourrzngcnlm112twoone8\n" +
                "nnqfmonerrpxeightfive9\n" +
                "klzrfbxjnznzkt24pjngplcdlftjz\n" +
                "66gbsllhhgxn38\n" +
                "threelzzrxspvq8four\n" +
                "qtvtpqspqflonetfrzvkthreeone8gsjqzgnv\n" +
                "9vhlxrqtdmzrpfqh74zsgnmsdlqgcp2\n" +
                "qkkkhxbrk35eightjpnmb761one\n" +
                "4vp4four49two\n" +
                "five6nrmvcfzlt665\n" +
                "skkqlzl1mrkgncmqnine68xvhfcsc\n" +
                "two17kbjcdsstlxst6\n" +
                "foureight3twonglgrv\n" +
                "6nine5\n" +
                "pgcmqzcfninepbgcrbzseven5zplhhbrjbpxj\n" +
                "sevensix6fourtwonpninebt\n" +
                "eight7951one\n" +
                "glvndtgdfkzzcbsmt36sevenfour3eight5\n" +
                "dtvgrkkzvhflhcsknhsccmxzgfivetcpz4zrcl9one\n" +
                "jpg3onenineqzjseven8phltdpjrsr8\n" +
                "68one\n" +
                "gctzfjksevenszfblxone2seven6pd\n" +
                "93nine42\n" +
                "two19four97crzhqndbqpmpvj\n" +
                "3six4mrntvlzntmqgcmms\n" +
                "1gmpdqpfkkz\n" +
                "xmsv3eightmdnqkdtzn814\n" +
                "395zqfqrgzs\n" +
                "9eight81cpnvrkkl\n" +
                "7rddzbqfm5fouronekxkhlgf1\n" +
                "fkclxddmxrpqzhqeight697\n" +
                "2mtvxtgq5six\n" +
                "3one9qvnpnmhzj6\n" +
                "rvvf3six9fourrq\n" +
                "r2eight55gvgpfs\n" +
                "dtztwofivefive12\n" +
                "three6zfqhnjzvr2twosevenoneightqp\n" +
                "sgleightwo2974c24\n" +
                "pplpgxnvzfpv4xlfive11four\n" +
                "58one\n" +
                "61four29\n" +
                "eightgxcgbrzd8five8\n" +
                "jxdzbxcc1one6pfivesixfiveg\n" +
                "two542cvjxvmhhthreexkl\n" +
                "three8nhzz4\n" +
                "sevenseven1seven14pxtwothree\n" +
                "mpdcbdjkp8ninethree\n" +
                "fourthreeg9pnine\n" +
                "onesixfourtckbkjdkqbfjkgpk54\n" +
                "qxh1twoclvzvsvgk2dvpkncltdt\n" +
                "fivefourhjckmndtdp98jzgqvrhbhxeighttdxkjltrdq\n" +
                "296dvxdxhdb4qbnmkzxh\n" +
                "djsrgct28vjkvsttnlf4\n" +
                "7rhdkfvqbxninegnkbgcqv1four42\n" +
                "seveneightdcb7sevenpdvqlmkvfive\n" +
                "39lr83hhhrfivexbhr\n" +
                "zx32sixeight\n" +
                "7hsxxzjjdh4rc55threeseven\n" +
                "5oneseven2sevenfourtwothree\n" +
                "9oneqc3seventwofive5\n" +
                "five2hnfkvsxmhjfivefivesix\n" +
                "3sixnine59three6mncxxxhkgxzlxscdzplm\n" +
                "eight9three62sixfour\n" +
                "26hfc4four1\n" +
                "jrnxgrvrctbg3nine\n" +
                "four73dqfiveeighttwosevenknq\n" +
                "94nine8fivevnvlnf\n" +
                "twopg79nine6kkpfgmpdlqhfc5\n" +
                "511twogghonefour\n" +
                "bvdneightsevenfcjnhccrlb7nine\n" +
                "lpfoneightfrnsrpgkzsixv8\n" +
                "1sevenseven981\n" +
                "53kvftth53fourc\n" +
                "zcmkkshveighteight1\n" +
                "9sixcrfzhfxzzrrdtkscp\n" +
                "8fhslkqzsc5jlpthreeninemjftx\n" +
                "rsfourfkglt1hfvhgeightfourvbmsnine\n" +
                "sixninefive5\n" +
                "2jqdfddkzzqxnkv8two\n" +
                "sevensevenmxhpqvmngfivecnhvg18\n" +
                "threesxrninenine31sixnmnssk\n" +
                "kzvvsvbjrfoursix6four\n" +
                "ckvmxptpxrvpsfvt9nine\n" +
                "66ninezgxttq1nineninexggjrtzgg7\n" +
                "two2eighthsrnine5pmptccfkfcpcmkn\n" +
                "seventqsqhbftscfonekdhrctnlcfdgzhvshsjgsbq7\n" +
                "nine1mdpxvlxkdx\n" +
                "pm4eighttwo\n" +
                "81ggljdxsthreeninefive\n" +
                "twofivenine39three\n" +
                "six152sixp\n" +
                "threemztwotwo5fiveseven\n" +
                "31twoninefsxmpsjx6eight\n" +
                "seven2deightone5threethree\n" +
                "hxmthvjphjdgctfpt4dfhxseven\n" +
                "4twoeightzx8\n" +
                "9dzbjqnnmbseven7\n" +
                "crdtprqs455onedmzvkzmmm\n" +
                "jqcxsxblgml1\n" +
                "9sbqzndbsx3twoseven7\n" +
                "eight8threezvvqbrsix34\n" +
                "ztzlrsg4qghxkvspvcsix2jndhxzfrm\n" +
                "6twovjkjgptwo43lg\n" +
                "1psnbrkbhb8seven\n" +
                "xfxqjrggpmtf4fivenine79\n" +
                "6pdv1xpsgr\n" +
                "zb4rqrqxsevenvklzmslqls\n" +
                "fourlstone7\n" +
                "53joneeight8ninef\n" +
                "1315\n" +
                "1qj4\n" +
                "djeightwocxrnf5fourone4eightbqj\n" +
                "jrgxvsmnzg5\n" +
                "twonsjbzvtqhgfivejdhxstbzrbtpndnjlvb7hhxfmrxtfxrcmjs\n" +
                "67xbctwo\n" +
                "7nbsrhcvrqj\n" +
                "fqnl9foursixtdgbcncr85three9\n" +
                "gmg4mr3rvdt\n" +
                "19qhmhvpzfour\n" +
                "pkptr6lssnqxncztpbt8\n" +
                "sjqtxbxp5twoseven1onerrsqghcfpncgkfour\n" +
                "7four8spgzfoureightthreedqp\n" +
                "two9bxlqs\n" +
                "deightwoninethree8\n" +
                "3plpprmmhvvsnvdzjzr9sqgbddpghthreejjmldhdqqm\n" +
                "sevenfiveseven4bkvxkzqbtxjvdsltfkn\n" +
                "sevenssfkdmvmntpxjpqlj8px\n" +
                "4hk9\n" +
                "fivenxcmhf78pmdd6mmqfvdxqbh7\n" +
                "five9hvfive7\n" +
                "eightfourrpflnfourtwo61\n" +
                "threenine2\n" +
                "ncdpjqcnine1twoonehglvzpzf\n" +
                "jmtpbhbshrvmhvqt38brsqpxn4one6\n" +
                "onesixvmmhsevenfoureight2six\n" +
                "ttwosix5nineb3eightthree\n" +
                "cmkdmhkdf3zdhjfmb\n" +
                "three5fiveqrrxrdtsixtwogntmvxsggqfive\n" +
                "oneeight5eightfive38twonegv\n" +
                "cqlfhlch924mpmqfvtwo\n" +
                "jrnzg5four3fivetwokxphktf\n" +
                "seveneightmzmzftx9gsmxjkj1stjbvxlvmlcdgnine\n" +
                "twonineeightninethree6blhm\n" +
                "3kskponetfgjgzphqtr\n" +
                "ntwo2\n" +
                "5six1vksjzrlgjnxtwovbkrdlhjsmzdxcf\n" +
                "twosixkfmcfndlj453two\n" +
                "six5twotzbzqtwo\n" +
                "fivenpcqfour5twonej\n" +
                "nineninefouroneztvqspscnk4twoklbht\n" +
                "bqcbm19hckcgtcfkb44eighttwo\n" +
                "52jcrbqbkhjx5nine8\n" +
                "5threethree\n" +
                "3twotrnnlstrndthree9\n" +
                "15zsnrfshn7twoeightsmvsfztx\n" +
                "789ckpxflvkr\n" +
                "skxlnpxxdgbhqnineninejsltrx8three\n" +
                "1sixone724\n" +
                "2seven4\n" +
                "7knspxrzszdbgc3seven\n" +
                "vsqmpf5sixsix9eightdtgmpxrksb\n" +
                "three6btwo11fived\n" +
                "bckqdndnine7bpzvkxkdqtwoseventxpzqg2\n" +
                "one6ntmlmfkfmjfourmgddpzfr5scjhhmgsix\n" +
                "four12mlhdscsxfiveonesevenlone\n" +
                "9rdlctlkc\n" +
                "11vjvjsllfivenv\n" +
                "2four6fourfive\n" +
                "5czmqmdkkthree3\n" +
                "sevenfive9\n" +
                "sevenfivemqjhqh9mvdkgtr\n" +
                "glvpdbbhxs9\n" +
                "four2three\n" +
                "six6gtdbttnhvkvh\n" +
                "5fcsbnpsixeightonetwo3\n" +
                "5psvznthreethreefive5qrkftfkqsix\n" +
                "36lmm\n" +
                "seven33onefournlr2\n" +
                "13seven\n" +
                "onejdxgxjpcsix1sevenpzbzthree\n" +
                "sevenqcjsxz6twokkpzllzqninetwo\n" +
                "1367mtsldgrdeightp\n" +
                "five111hbp9tlqp\n" +
                "threebbnine7onesix2twoneg\n" +
                "mxmpnxmpqponeeightktxvgkcdr7\n" +
                "411fourdhrdvrz\n" +
                "zxkmcr5eightkzqsixsix7\n" +
                "six972zleighttwonvgvth\n" +
                "vnmmbzfpttwofnjd76\n" +
                "twopnthreeqzlvkptmph9vnkbxghnone66\n" +
                "nine1fiveninethree4\n" +
                "mdrdpbsfcjsixpnxfour2four2\n" +
                "sgjrdtmzcj2mbnlbtqsdboneeight\n" +
                "9jbmhchfrnfqvxcjtwokrbjvzmcxrj\n" +
                "4jhjksqvnqsevennfrtslcgjbrhfour\n" +
                "6eightlzrrxfbcjeight5six1kzhtpbz\n" +
                "jqsmqbzpntxdfvdthreezrqzdhthreefmvslxk6\n" +
                "eight82two82zqghmbd\n" +
                "qtwone4d\n" +
                "6three16\n" +
                "9eightdmtkznh6\n" +
                "znc1185\n" +
                "eighteight665bxbngx5dvht2\n" +
                "9seven83three\n" +
                "mqdnhqfdgzfshjttvfour3hq92qtpdblnvdsxcskz\n" +
                "twofourfivedfffknb6ljxjlsq48\n" +
                "6pbdfrqpfour\n" +
                "vmtkqpjftc9twonej\n" +
                "rhcstmvxdnjgldpmlmsnineglmkntfiveeight3lgnlqmjkzl\n" +
                "rxzbjxjhkvhtxps2twohlcdgkrbdbmxvpf4five\n" +
                "1three9two\n" +
                "bp234jszvspdq\n" +
                "rcmhnmb3lpxneightfivetn7\n" +
                "srdh461fourcrhhkbxftghxqrptn\n" +
                "rlhlrm894\n" +
                "jtmmljgmmppknktqrbjtwod9\n" +
                "75kvnbm\n" +
                "psbcdponesix218\n" +
                "ndx5zthreetwokjjvzkjk\n" +
                "onerhnmsxmseven7two2snn34\n" +
                "nvmfj6hqdspmndlzqhrrznrpcgn\n" +
                "lqqgdmn5fivesfbqhveight1\n" +
                "one5pjpskd25four3\n" +
                "91dxxjkrthreethreefourfiverrdhqtwo\n" +
                "3sevenhbrznfcqmfivepqnmzxvlldhfdrvkqfmxzx8\n" +
                "lrfflx9pvrfctxkxk432\n" +
                "ninerhjlqfzg3fourbvfkbmxbntz1\n" +
                "6dkgtthreebjfgjqnv6lveight\n" +
                "seven527rgztslznxdkgrgf6one\n" +
                "npchxbnb5zpzrllhx777\n" +
                "rfour4qkvcxsbjnveightwogm\n" +
                "foursixsevenppnrdgpnrkbr5\n" +
                "3three4lm\n" +
                "1dmxvfour7\n" +
                "fiveh1eight\n" +
                "643\n" +
                "fivelsffmhsldlfkqkb2threek6three\n" +
                "23dpbpjcsqslnine4799\n" +
                "shvkdvntpmvt52dvclb5bjdj\n" +
                "eight5sevenfbjrpbdsdzhnc\n" +
                "dv2vqtqghlkprxx6three\n" +
                "four1six4fnznbcdghfzpd\n" +
                "eightfiveone4fourone\n" +
                "two75four85\n" +
                "3331\n" +
                "9eight1seven\n" +
                "9threexbsevenfour\n" +
                "22meight1\n" +
                "75two\n" +
                "five6onetwordjsgltj\n" +
                "oneseven9one\n" +
                "djljfzv7cnpnvhmqkjgn5eightsix97\n" +
                "three8xpskzk\n" +
                "nzgpp7fdcl6twotwochsgztwo\n" +
                "1tfvvmzfd4threekgqdthreesfxjggmszz\n" +
                "7krlgg8864gfp94\n" +
                "3xxpkqxfxcn\n" +
                "eighthl4cctb26bppqpsc\n" +
                "eight5rq\n" +
                "hncmdrmfive4\n" +
                "qml6mmx\n" +
                "qpckxnrjbdlprhmrqeight3bcjtghrrfvczqxeight\n" +
                "nine6five\n" +
                "fourmnzrtwocvdkmlc6\n" +
                "3sixseven1mnbdqfgcqqcpsix\n" +
                "ninekvxrhk2jjjrdlqf49\n" +
                "7seven743\n" +
                "xnrz1m5\n" +
                "cseven8pg2\n" +
                "hxbfzndh6nltvbv\n" +
                "7zxdkghnzrzljlqftwo7hfmptrgd\n" +
                "5jltxrmxn\n" +
                "9eightqskgfndxsgmsrprhsvnninellts\n" +
                "dz88\n" +
                "99nine\n" +
                "rphppqzzxk2four\n" +
                "2nzeight\n" +
                "four44two\n" +
                "qtwonetwodgbhqmtzf82onefive48\n" +
                "6fivedhmv\n" +
                "xsvpdrtvr28ltsjseven\n" +
                "foursixfour61nrseven\n" +
                "qrhtwone3tmtsixf\n" +
                "sqjvg2pzbzpgthreenine6cpsq\n" +
                "jlvnsbshjmxnxfouronesix2zlff5\n" +
                "rzxkpczkn1bkcfbpbcb\n" +
                "9nmkljlqmd9fivenine7fivexndtdghpc\n" +
                "6twovgpsevenmzcbjtnd3threegmsltfhrgq\n" +
                "fourmktnjsk4839ljqvqf\n" +
                "47hcbcnhjgxhdfn7rrbonehvlmddbone\n" +
                "26fchgtdnbtwo8jpqxkb\n" +
                "7dxtslxqkbqfivefive\n" +
                "sixnineqnjmseventwo5gh2c\n" +
                "three1eightvxeightwogrd\n" +
                "twotwoninesixxdvrxv5\n" +
                "sixonetqddfmone1seven7\n" +
                "fourseven9ninefoursxnnnfcbtb88\n" +
                "twonpbnblrh3qckkxckflprdnr4\n" +
                "6eighttwo2sevenqml\n" +
                "three1twotwon1cjfnnnlptc\n" +
                "tlqtgktgjtgfour24four91\n" +
                "ghseven56sevensixhfstvk\n" +
                "qd8fourvmvgmssixsix8oneightps\n" +
                "jjvhthplcgzdndmrnxmctrtnndmzztnggr9rspflsix\n" +
                "jqk39fivetwo\n" +
                "nine2sixrtwothree\n" +
                "gccjpxtcxfone6six6nine5\n" +
                "7twoeight8flzqk77\n" +
                "mjljctdbg8\n" +
                "sixthree8\n" +
                "bbdlvtsjhjst88\n" +
                "dklhhhlpqqxlgdzzheightjntbmlfour4\n" +
                "ggrbl5cthnzlsbjssixpt";
        int total = calibration(original);
        System.out.println("total is " + total);
    }

    public static int calibration(String text) {
        String[] lines = text.split("\n");
        // longest string in keySet is 5
        Map<String, String> map = Map.of(
                "one", "1",
                "two", "2",
                "three", "3",
                "four", "4",
                "five", "5",
                "six", "6",
                "seven", "7",
                "eight", "8",
                "nine", "9"
        );
        int total = 0;
        int lineIterator = 0;
        for (String line : lines) {
            int i = 0;
            int start = 0;
            while (start < line.length()) {
                String sub = line.substring(start, i + 1);
                //System.out.println(sub);
                if (sub.length() > 5) {
                    start++;
                    i = start;
                } else {
                    if (map.containsKey(sub)) {
//                        System.out.println("found match start = "  + start + " iterator = " + i);
                        line = line.replaceFirst(sub.substring(0, sub.length() -1), map.get(sub));
                        System.out.println(line);
                        start = i + 1 - sub.length() + 1;
                        i = start;
//                        System.out.println("restart line = " + line + " start = " + start + " iterator = " + i);
                    } else {
                        i++;
                    }
                }

                if (i == line.length()) {
                    start++;
                    i = start;
                }
            }
            System.out.println(line);
            lines[lineIterator] = line;
            lineIterator++;
        }
        System.out.println(total);
        for (String line : lines) {
            String lineNumOnly = line.replaceAll("([A-Z,a-z])", "");
            if (lineNumOnly.length() == 0) {
                total += 0;
            }
            else if (lineNumOnly.length() == 1) {
                total += Integer.parseInt("" + lineNumOnly.charAt(0) + lineNumOnly.charAt(0));
                System.out.println(line + " "  + lineNumOnly.charAt(0) + lineNumOnly.charAt(0));
            } else {
                total += Integer.parseInt("" + lineNumOnly.charAt(0) + lineNumOnly.charAt(lineNumOnly.length() - 1));
                System.out.println(line + " " + lineNumOnly.charAt(0) + lineNumOnly.charAt(lineNumOnly.length() - 1));
            }
        }
        return total;
    }
}